name: vsctheme
root: ~/projects/vsc-theme-gen
windows:
  - editor:
      panes:
        - sleep 5 && open http://localhost:8888
        - docker run -d -v ~/projects/vsc-theme-gen:/app -p 8888:8080 silesky/vscode-theme-gen:latest
