name: vsctheme
root: ~/projects/vsc-theme-gen
pre: code .
windows:
  - BACK:
      panes:
        - sleep 5 && open http://localhost:8888
        - docker run -it -d -v ~/projects/vsc-theme-gen/back:/app -p 8888:8080 silesky/vsc-theme-gen:latest
