name: vsc
root: ~/projects/vsc-theme-gen
pre: code .
windows:
  - BACK:
      root: ~/projects/vsc-theme-gen/back
      panes:
        - docker run -it -d -v ~/projects/vsc-theme-gen/back:/app -p 8888:8080 silesky/vsc-theme-gen:latest
  - FRONT:
      root: ~/projects/vsc-theme-gen/front
      panes:
        - webpack-dev-server
        - sleep 5 && open http://localhost:3001/index.bundle
